name: {{ cookiecutter.project_name }}
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - hydra-core
      - omegaconf
      - wandb
      - ruff
      - black
      - isort
      - pre-commit
      - mkdocs
      - mkdocs-material