name: {{ cookiecutter.project_name }}
channels:
  - conda-forge
dependencies:
  - python={{ cookiecutter.python_version }}
  - pip
  - pip:
      - hydra-core
      - omegaconf
      - wandb
      - ruff
      - black
      - isort
      - pre-commit
