name: {{cookiecutter.project_name}}
channels:
  - conda-forge
  - defaults
dependencies:
  - python={{cookiecutter.python_version}}
  - pip
  - pip:
      - hydra-core  
      - omegaconf
      - torch

  - black
  - pre-commit
  - isort
  - ruff