_target_: wandb.init

project: ${oc.env:WANDB_PROJECT,{{cookiecutter.project_name}}}
entity: ${oc.env:WANDB_ENTITY,null}

# DEFAULT = offline
mode: ${oc.env:WANDB_MODE,offline}

name: ${task}_${model.name}_${data.name}
tags: ${tags}

dir: ${paths.root_dir}/wandb