_target_: wandb.init
project: ${oc.env:WANDB_PROJECT,{{cookiecutter.project_name}}}
entity: ${oc.env:WANDB_ENTITY,null}
mode: ${oc.env:WANDB_MODE,online}
name: ${task}_${model.name}_${data.name}
tags: ${tags}
dir: .
