defaults:
  - _self_
  - data: mnist
  - model: mlp
  - trainer: gpu
  - logger: none
  - callbacks: default
  - paths: default
  - hydra: default
  - extras: default
  - experiment: baseline

task_name: train
tags: []
seed: 42

train: true
test: false

notes: null